### PR TITLE
Configure staging alias for Now and document production deployment

### PR DESCRIPTION
**Pull request by paulmelnikow**
Using this feature of Now for Git:

https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/#with-now-for-git

New commits to master should be auto-aliased to `raster.shields-server.com`.

I've a slight preference that we auto-deploy to staging and then build some kind of one-click deploy to production, though that would create a bit of extra work and I'm not sure it's worth it. If other folks think it's important that we do that, I'm open to pursuing it.

Happy to merge this now to get a feel of it, though when we decide on a real production alias (https://github.com/badges/shields/issues/3112#issuecomment-507065715) we'll need to update this domain name.

### CODE REVIEW

**Review by chris48s — APPROVED** [review]

**Comment by chris48s** [comment]
One thing we could do as a sort of halfway-house is deploy to staging, call a test URL. That way we've got a canary. If the deploy goes fine and the test works, then deploy to prod, otherwise stop there.

side issue: any reason why issues are off for this repo?

**Comment by paulmelnikow** [comment]
> One thing we could do as a sort of halfway-house is deploy to staging, call a test URL. That way we've got a canary. If the deploy goes fine and the test works, then deploy to prod, otherwise stop there.

So you're thinking the same, auto-deploy to staging / canary, and then a maintainer can manually alias the production domain.

> side issue: any reason why issues are off for this repo?

I turned them off for the moment to try to keep discussions centralized, as we've done with daily-tests. Though I'm open to us turning them back on.

Think there are tradeoffs either way. Centralized discussions means it's easier to keep track of the things that are happening and not lose track of things; decentralized means there's less noise about things that you're not interested in.

**Comment by chris48s** [comment]
Hmm.. might have slightly misunderstood the way the deploy works.

Is the way this will work

- `raster.shields.io` points at `foo.now.sh`
- we commit to this repo
- that kicks off a deploy deploy to `bar.now.sh`
- we alias `raster.shields.io` to point at `bar.now.sh` ?

if so, I'd propose that the ideal solution is we _automatically_ switch the alias, but only if `bar.now.sh/some/known/url` responds with a pre-defined expected response.

Don't really mind issues being off. Was just checking it was intent, rather than oversight..

**Comment by paulmelnikow** [comment]
> if so, I'd propose that the ideal solution is we _automatically_ switch the alias, but only if `bar.now.sh/some/known/url` responds with a pre-defined expected response.

Agreed it would be nice to smoke-test the deployed server before promoting it to production.

One possibility would be to make the required check happen in CI, though it's a little tricky because if we want it to hit the live server (i.e. the review app) it will need to wait for the deploy to finish. Alternatively we could check manually on PRs, maybe using a automatic review comment that posts a few links.

Another possibility would be a CI job that runs on master post-deploy, maybe using Github Actions, that waits for the new server to deploy, runs the smoke test, and then triggers the alias.

There's also now-pipeline: https://github.com/bahmutov/now-pipeline

**Comment by chris48s** [comment]
Right yes. I see what you mean - because the now deploy is a separate process, rather than a step in the Circle CI build, its more fiddly to script around it.

Happy to go with whatever allows us to get up and running quickly right now. I reckon we can probably let now.sh do it automatically given this is non-core functionality, but if you want to keep that step manual, that's definitely the more risk averse approach.

If we want to move to deploying shields.io itself in this way this is might be a useful place to experiment with a slightly more complex workflow.

**Comment by paulmelnikow** [comment]
> If we want to move to deploying shields.io itself in this way this is might be a useful place to experiment with a slightly more complex workflow.

:+1: to this. Let's set it up to auto-alias staging, and then we can start to build a process that allows us to promote to production in a transparent way.

I think Heroku is a better fit for the main badge server, though I think we can still get some good learning out of this.

**Comment by paulmelnikow** [comment]
The production aliasing isn't working quite correctly yet, though I think this is on the right track. I can update the docs once things are working as intended.

**Review by chris48s — DISMISSED** [review]

**Comment by paulmelnikow** [comment]
Okay, when this is merged `shields-raster-staging.now.sh` will auto-alias when commits are merged to master, and then to start with, there will be a manual step to alias `raster.shields.io`.

**Comment by calebcartwright** [comment]
Is this ready for a 👍 or still a WIP?

**Review by calebcartwright — APPROVED** [review]

**Comment by calebcartwright** [comment]
Approved anyway haha. Happy to re-👍 if more changes are needed

**Pull request merged**
